### ISSUE TITLE
Facing dependency  issue after upgrade solidus 3

### ISSUE THREAD

**Issue by dprabu17** [solidusio/solidus_stripe#114]
I am facing the following issue after upgrade solidus version. 

```
In Gemfile:
    solidus (= 3.0.1) was resolved to 3.0.1, which depends on
      solidus_core (= 3.0.1)

    solidus_stripe was resolved to 4.2.0, which depends on
      solidus_core (>= 2.3, < 3)
```

In the published [solidus_stripe](https://rubygems.org/gems/solidus_stripe) rubygems  mentioned  as below, 
```
RUNTIME DEPENDENCIES (3):
solidus_core >= 2.3, < 3
```

Please publish latest version in the rubygems. 
cc @kennyadsl

**Comment by ghost** [comment]
I'm having the same problem.

I'm guessing this is being blocked by the tests that have been failing for months related to some very complex multi-payment transactions.

I'm not sure if Stripe is a credible option with Solidus anymore.

**Comment by ghost** [comment]
#113 Is the same issue.

**Comment by kennyadsl** [comment]
Solidus 4.3.0 released
