### ISSUE TITLE
Clearer documentation on how to implement

### ISSUE THREAD

**Issue by stevenheffner** [solidusio/solidus_stripe#15]
The current documentation goes over how it install, but not how to actually implement this into a project. Ive been stuck on trying to figure this out for a few days now.

The main topics i've been stuck on are...

1. Do you have to set the source class for `Spree::PaymentMethod::StripeCreditCard` to `Spree::PaymentMethod::StripeCreditCard` (it defaults to Spree::CreditCard) or nil?. 
2. What does an example request body look like to the POST `orders/{order number}/payments` api when sending back a token?

**Comment by kennyadsl** [comment]
@stevenheffner sorry I don't get what you are trying to do (sorry for the delayed response). 

1. Why should you set the source class `Spree::PaymentMethod::StripeCreditCard` to `Spree::PaymentMethod::StripeCreditCard` and where?
2. Are you trying to make payments via API or using a standard Rails frontend (which I think is what this gem provides)?
