### ISSUE TITLE
Stripe checkout fails when using a stored credit card number

### ISSUE THREAD

**Issue by milesegan** [solidusio/solidus_stripe#16]
We're using this gem to implement stripe checkout and it works fine the first time the user places an order. But on subsequent checkouts it fails if the user selects the "Use an existing card on file" option on the payments page. It looks to me like the gem expects the user to enter a credit card every time but maybe I'm misreading the code. We get this JS error in the console:

```
TypeError: element.data is not a function
```

```
enableElement (jquery_ujs.self-784a997f6726036b1993eb2217c9cb558e1cbb801c6da88105588c56f13b466a.js?body=1:383)
(anonymous) (payment:363)
setTimeout (async)
(anonymous) (payment:362)
Promise.then (async)
(anonymous) (payment:359)
dispatch (jquery3.self-e200ee796ef24add7054280d843a80de75392557bb4248241e870fac0914c0c1.js?body=1:5238)
elemData.handle (jquery3.self-e200ee796ef24add7054280d843a80de75392557bb4248241e870fac0914c0c1.js?body=1:5045)```

**Comment by kennyadsl** [comment]
@milesegan are you using Stripe v2 or v3? With which Solidus version?

**Comment by milesegan** [comment]
@kennyadsl We're using Solidus 2.9.1 with stripe v3.

**Comment by kennyadsl** [comment]
I think I found the issue. Using v3, card checks are always executed, even when an existing card is selected. We should enable that JS, only when a user wants to add a new card. I plan to work on this during next week.

**Comment by milesegan** [comment]
That's great. Thanks for looking into this!

**Comment by kennyadsl** [comment]
Opened #17, which should fix the issue.
