### ISSUE TITLE
Handling of Strong Customer Authentication (SCA)

### ISSUE THREAD

**Issue by Aflier** [solidusio/solidus_stripe#18]
Using the the  Strong Customer Authentication (SCA) card (https://stripe.com/docs/payments/cards/testing) the payment cannot proceed. Payments from the EU countries will start failing. Thanks in advance.

**Comment by spaghetticode** [comment]
This should be a good starting point: https://stripe.com/docs/payments/payment-intents, specifically:

> Anyone affected by SCA should migrate to the Payment Intents API to take advantage of exemption logic and a simpler integration. Integrations using the Charges API are not SCA-ready.

I also confirm that in tests, using 3D secure test cards such as `4000 0000 0000 3220` will fail the payment:

<img width="958" alt="Schermata 2019-09-27 alle 14 40 50" src="https://user-images.githubusercontent.com/141220/65769817-d59e9680-e134-11e9-9b5f-402b760c8491.png">

**Comment by andyjeffries** [comment]
Without this change, it makes the gem pretty much unusable for anyone in the EU. Any updates? 

/cc: @kennyadsl (seems to be the main recent contributor)

**Comment by kennyadsl** [comment]
We know this is missing but at the moment we are able to contribute with things that are needed by our customers at Nebulab and if they want to share solutions with the rest of the community, which is pretty common. The real issue here is that we only have US customers using Stripe at the moment so we had no need of adding support for SCA yet.

Solidus is an open-source project so everyone is welcome to submit a PR for that.

**Comment by spaghetticode** [comment]
I'm working on this feature, but I can't put much time into it so it will take a while (I hope it will be done in one or two weeks).

**Comment by kennyadsl** [comment]
@spaghetticode thanks! I just found [this post on testing Stripe SCA with Capybara](https://gorails.com/blog/fill-in-stripe-elements-js-for-sca-3d-secure-2-and-capybara) that maybe could be useful.

**Comment by stuffmatic** [comment]
Hi! Any news on this?

**Comment by kennyadsl** [comment]
Yes, we are planning some work on this soon.

**Comment by leonjmac** [comment]
UK based dev here using this awesome gem. Have seen a few payment failures so far but not at a showstopper level. That said, if there's a branch where @spaghetticode, @kennyadsl, et al are working on implementing SCA compliance, please point me in the right direction as I'd like to help out... if I can!

**Comment by kennyadsl** [comment]
@leonjmac: yes, @spaghetticode has an alpha version [here](https://github.com/spaghetticode/solidus_stripe/commits/spaghetticode/payment-intents) with specs passing but there are still some things to do. If you could give it a test in the meantime (I would not use it in production yet) and give us some feedback it would be great. Thanks

**Comment by spaghetticode** [comment]
@leonjmac @stuffmatic @andyjeffries I opened this [PR](https://github.com/solidusio/solidus_stripe/pull/19) that hopefully is a good starting point in implementing SCA payments. 
If you feel like trying it, please let us know how it works.

**Comment by spaghetticode** [comment]
Closed via https://github.com/solidusio/solidus_stripe/pull/20
