### ISSUE TITLE
Preference :stripe_country is not defined on Spree::PaymentMethod::StripeCreditCard (RuntimeError)

### ISSUE THREAD

**Issue by shrmnk** [solidusio/solidus_stripe#27]
I'm unable to start my application after installing this payment method.

I am setting up a static configuration to pull the stripe credentials from the env:

```ruby
  config.static_model_preferences.add(
    Spree::PaymentMethod::StripeCreditCard,
    'stripe_env_credentials',
    secret_key: ENV['STRIPE_SECRET_KEY'],
    publishable_key: ENV['STRIPE_PUBLISHABLE_KEY'],
    stripe_country: 'SG',
    v3_elements: false,
    v3_intents: false,
    server: Rails.env.production? ? 'production' : 'test',
    test_mode: !Rails.env.production?
  )
```

---

On a side note, the installation step says to run

```
bundle exec rails g solidus_stripe:install
```

but that did not exist. I instead ran

```
bundle exec rails solidus_stripe:install:migrations
```

**Comment by kennyadsl** [comment]
Hey there, which version/git ref of the extension are you using? Can you please try to update to the latest ref?

**Comment by dylanwilbur** [comment]
I had the same problem. Solved by changing
`gem 'solidus_stripe', '~> 1.0.0'`
to
`gem 'solidus_stripe', git: 'https://github.com/solidusio/solidus_stripe'`
in the Gemfile
