### ISSUE TITLE
No gem found

### ISSUE THREAD

**Issue by straumer** [solidusio/solidus_stripe#4]
The gem doesn't seem to be at https://rubygems.org.

**Comment by aitbw** [comment]
Hi @straumer :wave: if you would like to use this gem, add it to your Gemfile like this:

`gem 'solidus_stripe', git: https://github.com/solidusio-contrib/solidus_stripe.git`

Let me know what you think!

**Comment by straumer** [comment]
Yep, did that. I'm testing it out at the moment. :)

**Comment by straumer** [comment]
Seems to do its job well with the solidus_backend and solidus_frontend. It'd also be nice if it had an option to use stripe.js version 3 out of the box, for better [PCI-Compliance](https://stripe.com/docs/security#validating-pci-compliance).

**Comment by tvdeyen** [comment]
Thanks for mentioning. Would you mind to open a new issue for that? This issue can be closed as well.
