### ISSUE TITLE
Custom stripe element field options (e.g for showing a credit card icon)

### ISSUE THREAD

**Issue by stuffmatic** [solidusio/solidus_stripe#41]
When using Stripe Elements, custom options can be passed when creating the `cardNumber`, `cardExpiry` and `cardCvc` fields. Among other things, these options can be used to specify 

* custom input field placeholders
* custom CSS classes 
* if the a credit card icon should be shown for the `cardNumber` field

See [the Stripe docs](https://stripe.com/docs/js/elements_object/create_element?type=cardNumber) for a complete list of options (use the green dropdown menu to switch between field types).

Here's an example of a `cardNumber` field with a custom placeholder and a credit card brand icon.

![cardnumber](https://user-images.githubusercontent.com/2444852/77407597-af417700-6db6-11ea-877b-5819bd9e6468.gif)

It would be nice to add overridable hooks for passing custom options. Maybe something like this:

```
SolidusStripe.Elements.prototype.cardNumberElementOptions = function () {
  return {
    style: this.baseStyle(),
    showIcon: true,
    placeholder: "I'm a custom placeholder!"
  }
}
```

```
this.elements.create('cardNumber', this.cardNumberElementOptions());
```

I'm happy to create a PR for this, but will wait for feedback on https://github.com/solidusio/solidus_stripe/pull/40 first since it touches the same code.

**Comment by aldesantis** [comment]
@stuffmatic I think this sounds great, would love to see a PR for it!
