### ISSUE TITLE
Better PCI-Compliance with stripe.js version 3

### ISSUE THREAD

**Issue by straumer** [solidusio/solidus_stripe#5]
As mentioned here:

Seems to do its job well with the solidus_backend and solidus_frontend. It'd also be nice if it had an option to use stripe.js version 3 out of the box, for better [PCI-Compliance](https://stripe.com/docs/security#validating-pci-compliance).

_Originally posted by @straumer in https://github.com/solidusio-contrib/solidus_stripe/issues/4#issuecomment-463804953_

**Comment by hkrdrm** [comment]
How is solidus_stripe implemented out the box.  Is it using ruby backend to communicate with stripe.  I've got SSL certs setup with lets encrypt are there any additional steps I need to take to make sure I'm compliant.  I was reading something in stripe about uploading extra documentation to them if your not using the js version of stripe.

**Comment by straumer** [comment]
For the better PCI-Compliance (not having to submit those extra docs), this gem needs an update for the solidus_frontend and solidus_backend OR you can make your own frontend that passes a payment token instead of credit card id to this payment method.

**Comment by jackie577** [comment]
Hi, just wondering if anyone is working on this. I have been getting this error: "Sending credit card numbers directly to the Stripe API is generally unsafe." Anyone know what is the best way to handle? There is an option in Stripe to check "I agree that I am unsafe" but that doesn't feel the most satisfying.

**Comment by spaghetticode** [comment]
[This PR](https://github.com/solidusio-contrib/solidus_stripe/pull/9) should allow addressing the issue.

**Comment by spaghetticode** [comment]
Closing after #9 was merged.
