### ISSUE TITLE
Auto capture behavior in v4.0.0

### ISSUE THREAD

**Issue by stuffmatic** [solidusio/solidus_stripe#50]
I just tried v4.0.0 of this gem and noticed that payments are not automatically captured, even though I have  `auto_capture` set to `true` in my config. I also tried setting auto capture to "Yes" via the admin interface without any luck. However, it seems like auto capturing works when using an existing card on file.

I noticed the following passage in the readme

_These charges are created uncaptured and will need to be captured in Solidus backend later, after the customer confirms the order_

Does this mean that I'll have to implement my own hook for automatically capturing payments when an order is completed? And is the auto capture option not used anymore? It would be great if someone could clarify.

**Comment by spaghetticode** [comment]
@stuffmatic autocapture is not viable with Payment Intents, as it would capture the money before the order is actually confirmed by the customer. That would be a problem if the customer decides to abandon the purchase, for example.

I'm thinking that another way to solve your problem would be making the payment the last step in the checkout process.

**Comment by stuffmatic** [comment]
@spaghetticode Thanks for the quick reply! ~~Out of curiosity, when Solidus auto captures a payment in a normal use case, does that happen before the order is confirmed? If so, that would mean that a customer abandoning the order between payment and confirmation will have paid for a non-completed order, right?~~ (the answer seems to be no)

I'm building an automated flow where orders are fulfilled without using the admin GUI and since `auto_capture=true` is not an option when using the payment intents API, I've added the following hook for capturing payments when orders are finalized:

```
Spree::Event.subscribe 'order_finalized' do |event|
  order = event.payload[:order]
  order.payments.pending.each do |payment|
    payment.capture!
  end

  Spree::OrderUpdater.new(order).update
end
```

Is this a reasonable approach or am I missing something?

Edit: answered my own question and added a description of my use case

**Comment by spaghetticode** [comment]
@stuffmatic sorry for the late answer. 

As you already know by now, the payment record is created in Solidus database right after the payment step, but the charge is actually executed only after the order is confirmed, as only at that time it makes sense to charge the customer (unless Stripe forces you to do it earlier with Payment Intents of course 😄 )

I think your code makes sense for the specific use case 👍
