### ISSUE TITLE
about LICENSE

### ISSUE THREAD

**Issue by ccarruitero** [solidusio/solidus_stripe#59]
I have some doubts about https://github.com/solidusio/solidus_stripe/commit/3a79c59ad5b4300d4c0e3a939d6c831536bcbf1b

I think the copyright notice in README could be `Copyright (c) 2020 Solidus Team and contributors` or something like these instead `Copyright (c) 2020 Spree Commerce Inc., released under the New BSD License`.

Also, I think it's ok to add another copyright notice in LICENSE, always that you don't remove the original.

```
Copyright (c) 2014 Spree Commerce Inc. and other contributors.
Copyright (c) 2020 Solidus Team and other contributors.
```

What do you think?

**Comment by spaghetticode** [comment]
Closing after #73
