### ISSUE TITLE
A token may not be passed in as a PaymentMethod. Instead, create a PaymentMethod or convert your token to a PaymentMethod by setting the `card[token]` parameter to 

### ISSUE THREAD

**Issue by TheSmokingDev** [solidusio/solidus_stripe#71]
Hi,

currently getting an error 
A token may not be passed in as a PaymentMethod. Instead, create a PaymentMethod or convert your token to a PaymentMethod by setting the `card[token]` parameter to 

spree.rb file
  config.static_model_preferences.add(
    Spree::PaymentMethod::StripeCreditCard,
    'stripe_env_credentials',
    secret_key: ENV['XXXXXX'],
    publishable_key: ENV[‘XXXXXX'],
    stripe_country: 'AUS',
    v3_elements: true,
    v3_intents: true,
    server: Rails.env.production? ? 'production' : 'test',
    test_mode: !Rails.env.production?
  )

Card used as per the test card 4000 0027 6000 3184
stripe admin

**Comment by andrewlynch** [comment]
@s3749653 I'm experiencing the same issue. How did you manage to resolve this?

**Comment by Chambeur** [comment]
For those who get the same issue, it seems to be because `elements` and `intents` should not be `true` at the same time:

```
    v3_elements: false,
    v3_intents: true
```
