### ISSUE TITLE
How to specify API version

### ISSUE THREAD

**Issue by dankmitchell** [solidusio/solidus_stripe#93]
How do I specify the API version to ensure SCA compliance? i..e https://stripe.com/docs/api/versioning?lang=ruby

In my case the old API version is still being used -

<img width="1146" alt="Screenshot 2020-12-16 at 09 58 54" src="https://user-images.githubusercontent.com/3071606/102646046-4f1c0d80-415b-11eb-9002-9b204425f7cb.png">

**Comment by kennyadsl** [comment]
Can you please point out why using the old API version would not ensure SCA compliance?

**Comment by chrean** [comment]
Got no answer on this one, closing, please feel free to create a new one if necessary.
